name: CI / Build Project

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '50 23 * * *' # Everyday at 11:50 PM UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies and fund
      run: |
        npm install
        npm fund

    - name: Build the Project
      run: |
        npm run build
        echo Build Successful.
    
    - name: Finalize the Results
      run: |
        echo Everthing Good to Go.